In [ ]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

In [ ]:
reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [ ]:
one_hot("amazing restaurant",30)

[17, 3]

In [ ]:
vocab_size=30
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
encoded_reviews

[[18, 29],
 [17, 3],
 [20, 12],
 [13, 13, 26],
 [6, 2, 15],
 [12, 29],
 [18, 2, 9],
 [2, 25],
 [2, 19],
 [5, 13]]

In [ ]:
max_length=3
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
padded_reviews

array([[18, 29,  0],
       [17,  3,  0],
       [20, 12,  0],
       [13, 13, 26],
       [ 6,  2, 15],
       [12, 29,  0],
       [18,  2,  9],
       [ 2, 25,  0],
       [ 2, 19,  0],
       [ 5, 13,  0]], dtype=int32)

In [ ]:
embeded_vector_size = 5

model = Sequential()
model.add(Embedding(vocab_size, embeded_vector_size, input_length=max_length,name="embedding"))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [ ]:
X = padded_reviews
y = sentiment

In [ ]:
X = padded_reviews
y = sentiment

In [ ]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])


In [ ]:
model.fit(X, y, epochs=50, verbose=0)

In [ ]:
loss, accuracy = model.evaluate(X, y)
accuracy

1/1 [==============================] - 0s 156ms/step - loss: 0.5366 - accuracy: 1.0000


1.0

In [ ]:
weights = model.get_layer('embedding').get_weights()[0]
weights

array([[ 1.25839770e-01,  9.27481055e-02, -9.42110568e-02,
        -1.35777444e-01,  1.01956919e-01],
       [-2.76246425e-02, -4.82040308e-02,  4.59013470e-02,
        -2.63031479e-02,  1.33023299e-02],
       [-6.64718002e-02,  1.36784792e-01, -1.31970927e-01,
         1.08452007e-01,  9.41648930e-02],
       [ 8.89926329e-02, -9.62874740e-02,  5.71399294e-02,
        -7.12132230e-02, -1.06212474e-01],
       [ 3.76310088e-02, -4.74582426e-02,  3.01545300e-02,
        -1.55541785e-02, -3.08994055e-02],
       [-1.41427219e-01,  1.32159933e-01, -7.47097433e-02,
         1.42404824e-01,  7.15756714e-02],
       [ 8.20207670e-02, -1.11426987e-01,  1.33510217e-01,
        -9.27414596e-02, -5.25557101e-02],
       [-4.09078225e-02,  1.26127638e-02,  3.75830643e-02,
         1.22450292e-04, -1.80392265e-02],
       [ 3.36438678e-02,  4.42955606e-02,  3.45335342e-02,
         1.87588446e-02,  3.55255492e-02],
       [ 8.72632265e-02,  5.84528334e-02, -1.43398628e-01,
        -9.10082534e-02

In [ ]:
weights[18]

array([ 0.04458049, -0.06017823,  0.05484772, -0.08804639, -0.04146066],
      dtype=float32)

In [ ]:
weights[17]

array([ 0.08442494, -0.09450519,  0.12928435, -0.09857739, -0.06667444],
      dtype=float32)